[phases.setup]
nixPkgs = ["ffmpeg", "wget"]

[phases.install]
cmds = [
  "npm install",
  "cd server && wget -O silk_v3_decoder https://github.com/kn007/silk-v3-decoder/releases/download/v1.0.0/silk_v3_decoder_linux || echo 'silk_v3_decoder download failed'",
  "cd server && chmod +x silk_v3_decoder || echo 'chmod failed'"
]

[start]
cmd = "npm start"